version: "3.9"
services:
  auth_service:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: dev
    container_name: ${SERVICE_NAME}
    ports:
      - ${EXPORTED_APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
